# Generated by Django 4.2.29 on 2026-04-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_initial'),
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recurrence_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10)),
                ('payment_method', models.CharField(choices=[('debit', 'Débito'), ('pix', 'PIX'), ('cash', 'Dinheiro'), ('transfer', 'Transferência'), ('credit', 'Crédito')], max_length=15)),
                ('day_of_month', models.IntegerField(help_text='Dia do mês (1-31) ou N-ésimo dia útil')),
                ('use_business_day', models.BooleanField(default=False, help_text='Se True, usa o N-ésimo dia útil do mês')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='categories.category')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='credit_cards.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['description'],
            },
        ),
    ]
