# Generated by Django 4.2.29 on 2026-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrences', '0002_recurrence_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='debtor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='is_receivable',
            field=models.BooleanField(default=False, help_text='Se True, os lançamentos gerados são cobranças (a receber)'),
        ),
    ]
