# Generated by Django 4.2.29 on 2026-04-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
        ('recurrences', '0001_initial'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='competence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.creditcard'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debtor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_receivable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('partial', 'Recebido Parcial'), ('received', 'Recebido')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='recurrences.recurrence'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
