# Generated by Django 5.2.13 on 2026-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_is_partial_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_invoice_payment',
            field=models.BooleanField(default=False, help_text='Lançamento de quitação de fatura (saída da conta corrente). O gasto em si já foi contado nos lançamentos de crédito com competence_date no mês da fatura — esse aqui é só a baixa em dinheiro, e entra por fora dos relatórios mensais de receita/despesa para não contar o mesmo gasto duas vezes.'),
        ),
    ]
