# Generated by Django 5.2.13 on 2026-09-15 12:20

from django.db import migrations


def mark_existing_invoice_payments(apps, schema_editor):
    """Lançamentos de quitação de fatura sempre foram criados com notes
    começando em 'Fatura ID <id>' (ver apps/credit_cards/schema.py pay_invoice).
    Sem essa flag, o valor pago entrava contado duas vezes nos relatórios
    mensais: uma como o gasto original no cartão (competence_date) e outra
    como a baixa em dinheiro (esse lançamento)."""
    Transaction = apps.get_model("transactions", "Transaction")
    Transaction.objects.filter(
        payment_method="pix",
        transaction_type="expense",
        notes__startswith="Fatura ID ",
    ).update(is_invoice_payment=True)


def unmark(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")
    Transaction.objects.filter(is_invoice_payment=True).update(is_invoice_payment=False)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_is_invoice_payment'),
    ]

    operations = [
        migrations.RunPython(mark_existing_invoice_payments, unmark),
    ]
