# Generated by Django 5.2.17 on 2026-08-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "initial_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor que o usuário já tinha guardado quando criou a meta",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Aporte mensal fixo desta meta. Se vazio, o rateio automático decide.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Menor valor = maior prioridade no rateio sequencial",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Prazo desejado (opcional) — usado só para comparar com a projeção",
                        null=True,
                    ),
                ),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("icon", models.CharField(blank=True, default="target", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("completed", "Concluída"),
                            ("archived", "Arquivada"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conta onde o dinheiro da meta fica guardado (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goal_contributions",
                        to="accounts.account",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aporte",
                "verbose_name_plural": "Aportes",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalPlanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor máximo por mês destinado às metas. Vazio = usa a sobra mensal calculada.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequencial (uma meta por vez)"),
                            ("proportional", "Proporcional (todas ao mesmo tempo)"),
                        ],
                        default="sequential",
                        max_length=15,
                    ),
                ),
                (
                    "months_window",
                    models.IntegerField(
                        default=3,
                        help_text="Quantos meses fechados são usados para calcular as médias de gastos",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_plan_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de metas",
                "verbose_name_plural": "Planos de metas",
            },
        ),
    ]
