# Generated by Django 4.2.29 on 2026-04-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('other', 'Outro')], default='visa', max_length=15)),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_day', models.IntegerField(help_text='Dia de fechamento (1-31)')),
                ('due_day', models.IntegerField(help_text='Dia de vencimento (1-31)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='Conta usada para pagamento da fatura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_cards', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(help_text='Primeiro dia do mês de referência')),
                ('closing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('paid', 'Paga'), ('partial', 'Paga Parcial')], default='open', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='credit_cards.creditcard')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-reference_month'],
                'unique_together': {('credit_card', 'reference_month')},
            },
        ),
    ]
