# Generated by Django 5.2.13 on 2026-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parte da fatura que foi parcelada para as faturas seguintes', max_digits=12),
        ),
    ]
